create table if not exists person (
    id integer generated by default as identity primary key,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    date_of_birth date not null,
    email varchar(100) unique not null,
    password varchar not null,
    role varchar(100) not null,
    registered_at timestamp not null
);

create table if not exists book (
    id integer generated by default as identity primary key,
    title varchar(100) not null,
    author varchar(100) not null,
    description text not null,
    copies integer not null check (copies >= 0),
    copies_available integer not null check (copies_available >= 0),
    img text not null
);

create table if not exists genre (
    id integer generated by default as identity primary key,
    description varchar(50) unique not null
);

create table if not exists book_genre (
    book_id integer not null references book (id) on delete cascade,
    genre_id integer not null references genre (id) on delete cascade,
    primary key(book_id, genre_id)
);

create table if not exists checkout (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    book_id integer not null references book (id) on delete cascade,
    checkout_date date not null,
    return_date date not null
);

create table if not exists review (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null,
    person_first_name varchar(100) not null,
    person_last_name varchar(100) not null,
    book_id integer not null references book (id) on delete cascade,
    date timestamp not null,
    rating decimal(3, 2) not null,
    review_description text
);

create table if not exists history_record (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    book_id integer not null references book (id) on delete cascade,
    checkout_date date not null,
    return_date date not null
);

create table if not exists discussion (
    id integer generated by default as identity primary key,
    person_email varchar(100) not null references person (email) on delete cascade,
    title varchar(100) not null,
    question text not null,
    admin_email varchar(100),
    response text,
    closed boolean default false not null
);

create table if not exists payment (
    id integer generated by default as identity primary key,
    person_email varchar(100) unique not null references person (email) on delete cascade,
    amount decimal(10, 2) not null
);